
#############
## lecture du tableau des echantillons
info_samples <- read.table("louis2.csv", header=TRUE, sep=";", dec = ",", stringsAsFactors = FALSE)

str(info_samples)
head(info_samples)
tail(info_samples)


## exploration: statistiques descriptives
########################################

## Que pensez-vous de l'identifiant?
info_samples$identifiant <- as.character(info_samples$identifiant)
str(info_samples)

## QUALTATIVES
## Quelles sont les valeurs possibles des variables qualitatives?

unique(info_samples$genre)
unique(info_samples$origine)
unique(info_samples$tabac)

#Combien d'occurences observe-t-on pour chaque valeur de ces varaibles?'
table(info_samples$genre)
table(info_samples$tabac)
table(info_samples$origine)

# grouper Am du Nord et latine
info_samples$origine[which(info_samples$origine == "AMERIQUE DU NORD")] <- "AMERIQUE"
info_samples$origine[which(info_samples$origine == "AMERIQUE LATINE")] <- "AMERIQUE"

# représenter les distributions de ces variables
pie(table(info_samples$tabac))
pie(table(info_samples$genre), col=c("pink", "blue"),
    labels = c("Femmes", "Hommes"), main="Pie chart of the gender variable in the sample")
pie(table(info_samples$origine), main="Pie chart of the origine variable in the sample", cex=0.5, clockwise = T)

# Les camemberts ne sont pas des bonnes représentations. La représentation de données catégoriques recommandée est le diagramme en bâtons.
# tableaux de contingences:
barplot(table(info_samples$origine)/length(info_samples$origine), main="Distribution of the origine variable", ylab="frequency")

table(info_samples$genre, info_samples$origine)
barplot(table(info_samples$genre, info_samples$origine), main="Distribution of the origine variable with the variable gender stacked", col = c("pink", "blue") )

barplot(table(info_samples$origine, info_samples$genre), main="Distribution of the origine variable with the variable gender stacked") 

table(info_samples$genre, info_samples$tabac)
barplot(table(info_samples$tabac, info_samples$genre)/dim(info_samples)[1], main="Distribution of the tabac variable with the variable gender stacked", ylim=c(0,1)) 

## test stat sur variables qualtitaives
chisq.test(info_samples$tabac, info_samples$genre)
chisq.test(info_samples$tabac, info_samples$genre)$p.value

#table(info_samples$genre, info_samples$tabac)[1,]/sum(table(info_samples$genre, info_samples$tabac)[1,])
#table(info_samples$genre, info_samples$tabac)[2,]/sum(table(info_samples$genre, info_samples$tabac)[2,])


## VA QUANTITATIVES
#variables quantitatives continues:
summary(info_samples[,c(3,6:13)])
hist(info_samples$taille)
hist(info_samples$poids, freq=F)
lines(density(info_samples$poids), col="red")

boxplot(info_samples$taille)
boxplot(info_samples$poids)

par(mfrow=c(3,1))
stripchart(info_samples$poids, vertical = F, axes=F, main="Distribution du poids")
hist(info_samples$poids, freq=F, xlab="", main="")
boxplot(info_samples$poids, horizontal = T, frame.plot=F, xlab="Poids")

## Quelle est l'influence des variables qualitatives sur ces distributions?
boxplot (info_samples$taille ~ factor(info_samples$origine))
boxplot (info_samples$taille ~ factor(info_samples$zone, levels=c("Nord", "Centre", "Sud")), xlab="Region", ylab="taille")

par(mfrow=c(2,2))
boxplot (info_samples$taille ~ info_samples$origine, xlab="Region", ylab="taille", col = "steelblue3")
boxplot (info_samples$poids ~ info_samples$origine, xlab="Region", ylab="poids", col = "steelblue3")
boxplot(info_samples$taille ~ info_samples$genre, xlab="Genre", ylab="taille", col = "steelblue3")
boxplot(info_samples$poids ~ info_samples$genre, xlab="Genre", ylab="poids", col = "steelblue3")

## Tests stats:

## poids selon le sexe:
by(info_samples$poids, info_samples$genre, mean)
by(info_samples$poids, info_samples$genre, var)
var.test(info_samples$poids[info_samples$genre=="F"],info_samples$poids[info_samples$genre=="M"])
t.test(info_samples$poids ~ info_samples$genre, var.equal=T)

by(info_samples$taille, info_samples$genre, mean)
by(info_samples$taille, info_samples$genre, var)
var.test(info_samples$taille[info_samples$genre=="F"],info_samples$taille[info_samples$genre=="M"])
t.test(info_samples$taille ~ info_samples$genre)
t.test(info_samples$taille ~ info_samples$genre)$p.value

by(info_samples$poids, info_samples$tabac, mean)
by(info_samples$poids, info_samples$tabac, var)
bartlett.test(taille~tabac, data=info_samples)

# new variable
info_samples$imc_cat <- NA
info_samples$imc_cat[info_samples$imc<18.5] <- "maigreur"
info_samples$imc_cat[info_samples$imc>=18.5 & info_samples$imc<25] <- "normal"
info_samples$imc_cat[info_samples$imc>=25 & info_samples$imc<30] <- "surpoids"
info_samples$imc_cat[info_samples$imc>=30] <- "obesite"
info_samples$imc_cat <- factor(info_samples$imc_cat, levels=c("normal", "maigreur", "surpoids", "obesite"))
by(info_samples$poids, info_samples$imc_cat, mean)
by(info_samples$poids, info_samples$imc_cat, var)
bartlett.test(poids~imc_cat, data=info_samples)

# more than 2 levels
kruskal.test(log(info_samples$TG) ~ info_samples$imc_cat)
summary(aov(log(info_samples$TG) ~ info_samples$imc_cat))
summary(lm(log(info_samples$TG) ~ info_samples$imc_cat))


## Correlation - covariance:
plot(data=info_samples, log(TG)~imc)
abline(lm(data=info_samples, log(TG)~imc), col="red")

plot(data=info_samples, poids~imc)
abline(lm(data=info_samples, poids~imc), col="red")


library(dabestr)



