---
title: "Analysis of omics data from Pavkovic 2019 - Feature selection"
author: "Jacques van Helden and Denis Puthier"
date: '`r Sys.Date()`'
output:
  html_document:
    self_contained: no
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: "hide"
  ioslides_presentation:
    slide_level: 2
    self_contained: no
    colortheme: dolphin
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    smaller: yes
    toc: yes
    widescreen: yes
  slidy_presentation:
    smart: no
    slide_level: 2
    self_contained: yes
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
  revealjs::revealjs_presentation:
    theme: night
    transition: none
    self_contained: true
    css: ../slides.css
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  powerpoint_presentation:
    slide_level: 2
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    toc: yes
font-import: http://fonts.googleapis.com/css?family=Risque
subtitle: DUBii 2020
font-family: Garamond
transition: linear
editor_options: 
  chunk_output_type: console
---


## ANOVA-based variable ordering (multiple subtypes)

The **ANOVA** test allows to select genes whose inter-group variance is significantly higher than the so-called **residual variance**, i.e. the variance remaining after removing the inter-group variance from the todal variance.  

In the context of detection of differentially expressed genes, ANOVA can be thought of as generalization of the Welch test. Indeed, Welch and Student tests were conceived to test the equality of the mean between two groups (for example one subtype of interest and all the other subtypes), whereas ANOVA simultaneously tests the equality of the mean for multiple groups. 


$$H_0= \mu_1 = \mu_2= \cdots = \mu_g$$

We could thus use ANOVA to establish a general ranking criterion that would select the genes showing higest differences between ALL subtypes, without specifying a priori which particular subtypes have to be different. 

In a first time, we will apply the ANOVA test to one arbitrarily selected gene. We will then see how to run this test on each row of the expression matrix.


Some remarks about the implementation.

1. In contrast with the Welch test, which was a 2-groups test, ANOVA can be used to compare multiple groups in a single analysis. For ANOVA, we will use the original sample labels (with all the ALL subtypes explicitly named), rather than the `one.vs.other` vector that we created for 2-groups analysis.

2. We will run a  single-factor ANOVA, with gene expression as values, and sample labels as grouping.

3. The R methods `aov()` and `anova()` take as input a data frame with the values (gene expression values) in the first column, and the groupings (sample labels) in the second one.

4. **R** proposes two methods for the ANOVA test. The `aov()` function automatically fits a linear model and runs the anova test. However it is conceived for balanced groups (all groups should have smiliar effectives), which is not our case (some of the ALL subtypes have very few samples). With our data, it returns a warning *"Estimated effects must be unbalanced"*. Hereafter we will run both approaches to illustrate their implementation., but the second one (`anova()`) is the most flexible.

5. Even though `anova()` can handle unbalanced groups, we should keep in mind that the power of the test depends on the fact that we dispose of a sufficient number of samples per group. It might thus be wise to restrict the analysis to the groups containing a minimum number of samples (for example at least 8). 


```{r}
i <- 123 ## Select an arbitrary feature

x <- log2Filtered

## Build a data frame with gene expression values in the first column, 
## and sample labels in the second column.
expr <- unlist(x[i,]) ## Select the expression profile for this feature
g.for.anova <- data.frame("expr"=g.expr, "group"=sample.labels)

## Run the aov() method to check the warnings
g.aov.result <- aov(formula = expr ~ group, data = g.for.anova)
print(g.aov.result)


## We thus try the indirect approach: fit a linear model and run anova on it.
g.anova.result <- anova(lm(formula = expr ~ group, data = g.for.anova))
print(g.anova.result)

## Extract the p-value from the ANOVA result
attributes(g.anova.result)
pval <- as.numeric(unlist(g.anova.result)["Pr(>F)1"])
print(pval)

## Compute the e-value from this p-value
eval <- pval * nrow(denboer2009.expr)
print(eval)

## Summarise the result in a vector
g.anova.summary <- data.frame("g"=g, 
                     "name"=row.names(denboer2009.expr[g,]),
                     "pval"=pval,
                     "eval"=eval,
                     "sig"=-log(eval, base=10))
kable(g.anova.summary, caption = "Anova result for an aribtrary gene. ")
```
